[package]
name = "viter"
version = "0.1.0"
authors = ["mbme"]

[dependencies]
time = "0.1"
rusqlite = "0.9"
iron = "0.4"
router = "0.4"
mime_guess = "1.8"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
url = "1.2"

[dependencies.multipart]
version = "0.9"
features = ["iron"]
